### ISSUE TITLE
Unzip errors

### ISSUE THREAD

**Issue by HankBrown** [studiopress/genesis-sample#231] opened 2019-04-15 16:25 UTC
**Describe the bug**
npm run zip creates a file which generates these errors:

```
 ... more...
  error:  invalid compressed data to inflate
  inflating: genesis-sample/README.txt
  inflating: genesis-sample/screenshot.png
  error:  invalid compressed data to inflate
  inflating: genesis-sample/style.css
  error:  invalid compressed data to inflate```

**To reproduce**
Steps to reproduce the behavior:
1.  git clone
2. npm install
3. composer install
4. npm run zip

**Expected behavior**

unzip without errors

**Screenshots**


**System information (please complete)**
 - macOS 10.13.4
 - Chrome 73.0.3683.103  


**Additional context**

Run "git archive -o genesis-sample.zip --prefix=genesis-sample/ HEAD"  creates a workable zip.

The final result compares perfectly with a download and install via WP. So this is not a big deal. I''m just not sure if it means I may run into more trouble later... have had no issues with zip on a mac for over a decade... so forget what else to check for. File permissions appear normal and valid.

**Comment by nickcernis** [comment] 2019-04-15 17:16
Thanks for the report, @HankBrown. I couldn't reproduce this, but am running macOS 10.14.4 rather than 10.13.4. If you have time to share some extra info, it may help us learn more.

1. Are you cloning the latest develop branch that has the new `.scripts/makezip.js` script?
2. Are you unzipping with the macOS Archive Utility or another app?
3. Can you share the output of `npm run zip --verbose`, please (from the first `npm info it worked if it ends with ok` to the last `npm info ok`?

**Comment by jb510** [comment] 2019-04-15 17:41
FWIW - also unable to reproduce 
macOS 10.14.4
unzipping with CLI `unzip` successful (UnZip 6.00 of 20 April 2009, by Info-ZIP.)
unzipping with macOS `Archive Utility` successful 
unzipping with `Keka` successful

for comparison:
```
± % npm run zip --verbose                                                                                                                         !4689
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node@10/10.15.2/bin/node',
npm verb cli   '/usr/local/opt/node@10/bin/npm',
npm verb cli   'run',
npm verb cli   'zip',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.15.2
npm verb run-script [ 'prezip', 'zip', 'postzip' ]
npm info lifecycle genesis-sample@~prezip: genesis-sample@
npm info lifecycle genesis-sample@~zip: genesis-sample@

> genesis-sample@ zip /Users/jon/Sites/genesis/app/public/wp-content/themes/genesis-sample
> node .scripts/makezip.js

Renaming .md files to .txt
Making zip file
Created genesis-sample.zip, 1.1 MB
Renaming .txt files to .md
npm verb lifecycle genesis-sample@~zip: unsafe-perm in lifecycle true
npm verb lifecycle genesis-sample@~zip: PATH: /usr/local/Cellar/node@10/10.15.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jon/Sites/genesis/app/public/wp-content/themes/genesis-sample/node_modules/.bin:/usr/local/opt/node@10/bin:/Users/jon/.node/bin:/Users/jon/.composer/vendor/bin:/Users/jon/pear/bin:/Users/jon/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:~/pear/bin:~/pear/share/pear:~/bin:~/.composer/vendor/bin:~/.node/bin:/usr/bin/java:/Users/jon/.rvm/bin
npm verb lifecycle genesis-sample@~zip: CWD: /Users/jon/Sites/genesis/app/public/wp-content/themes/genesis-sample
npm info lifecycle genesis-sample@~postzip: genesis-sample@
npm verb exit [ 0, true ]
npm timing npm Completed in 536ms
npm info ok
```

**Comment by HankBrown** [comment] 2019-04-15 20:41
```
book17-2:genesis brownhanky$  npm run zip --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'run',
npm verb cli   'zip',
npm verb cli   '--verbose' ]
npm info using npm@6.7.0
npm info using node@v10.14.2
npm verb run-script [ 'prezip', 'zip', 'postzip' ]
npm info lifecycle genesis-sample@~prezip: genesis-sample@
npm info lifecycle genesis-sample@~zip: genesis-sample@

> genesis-sample@ zip /Users/brownhanky/home/brownhanky/sites/genesis
> run-s build:export-zip build:md-to-txt

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
npm verb cli   'run',
npm verb cli   'build:export-zip' ]
npm info using npm@6.7.0
npm info using node@v10.14.2
npm verb run-script [ 'prebuild:export-zip',
npm verb run-script   'build:export-zip',
npm verb run-script   'postbuild:export-zip' ]
npm info lifecycle genesis-sample@~prebuild:export-zip: genesis-sample@
npm info lifecycle genesis-sample@~build:export-zip: genesis-sample@

> genesis-sample@ build:export-zip /Users/brownhanky/home/brownhanky/sites/genesis
> git archive -o genesis-sample.zip --prefix=genesis-sample/ HEAD

npm verb lifecycle genesis-sample@~build:export-zip: unsafe-perm in lifecycle true
npm verb lifecycle genesis-sample@~build:export-zip: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brownhanky/home/brownhanky/sites/genesis/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brownhanky/home/brownhanky/sites/genesis/node_modules/.bin:/Applications/Bento4-SDK-1-4-3-608.universal-apple-macosx/bin:/usr/local/bin:/Users/brownhanky/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin:/Users/brownhanky/.rvm/bin:./npm
npm verb lifecycle genesis-sample@~build:export-zip: CWD: /Users/brownhanky/home/brownhanky/sites/genesis
npm info lifecycle genesis-sample@~postbuild:export-zip: genesis-sample@
npm verb exit [ 0, true ]
npm timing npm Completed in 175ms
npm info ok
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
npm verb cli   'run',
npm verb cli   'build:md-to-txt' ]
npm info using npm@6.7.0
npm info using node@v10.14.2
npm verb run-script [ 'prebuild:md-to-txt',
npm verb run-script   'build:md-to-txt',
npm verb run-script   'postbuild:md-to-txt' ]
npm info lifecycle genesis-sample@~prebuild:md-to-txt: genesis-sample@
npm info lifecycle genesis-sample@~build:md-to-txt: genesis-sample@

> genesis-sample@ build:md-to-txt /Users/brownhanky/home/brownhanky/sites/genesis
> node .scripts/md-to-txt.js

Renaming .md files to .txt files inside the zip...
Done renaming .md files to .txt. Please test the new zip file...
npm verb lifecycle genesis-sample@~build:md-to-txt: unsafe-perm in lifecycle true
npm verb lifecycle genesis-sample@~build:md-to-txt: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brownhanky/home/brownhanky/sites/genesis/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brownhanky/home/brownhanky/sites/genesis/node_modules/.bin:/Applications/Bento4-SDK-1-4-3-608.universal-apple-macosx/bin:/usr/local/bin:/Users/brownhanky/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin:/Users/brownhanky/.rvm/bin:./npm
npm verb lifecycle genesis-sample@~build:md-to-txt: CWD: /Users/brownhanky/home/brownhanky/sites/genesis
npm info lifecycle genesis-sample@~postbuild:md-to-txt: genesis-sample@
npm verb exit [ 0, true ]
npm timing npm Completed in 244ms
npm info ok
npm verb lifecycle genesis-sample@~zip: unsafe-perm in lifecycle true
npm verb lifecycle genesis-sample@~zip: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brownhanky/home/brownhanky/sites/genesis/node_modules/.bin:/Applications/Bento4-SDK-1-4-3-608.universal-apple-macosx/bin:/usr/local/bin:/Users/brownhanky/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin:/Users/brownhanky/.rvm/bin:./npm
npm verb lifecycle genesis-sample@~zip: CWD: /Users/brownhanky/home/brownhanky/sites/genesis
npm info lifecycle genesis-sample@~postzip: genesis-sample@
npm verb exit [ 0, true ]
npm timing npm Completed in 1218ms
npm info ok
```

dev version? No. I specifically switched back to master because (I forget already).
OK I see this is being addressed and I should have read the instructions more carefully.
Something about excluding npm_modules I think.

I purchased the Design Pro plugin. It's quite hard for me to figure it out, whereas generating css from sass is easy for me. Then I discover Design Pro doesn't work with the this theme!!

My real question is this: I wanted to use the sass partials given by the prometheus theme (https://github.com/srikat/genesis-sample-sass) , but they were generated for genesis 2.6, and genesis is now at 2.9.1... it is not clear to me if/how those get updated. Maybe they never will and it is up to us?

The point is to try to leverage my existing sass palette. I begin to doubt it is worth chasing. If I have to keep the sass partials updated whenever genesis updates.

Thank you for your patience with my ignorance.

**Comment by nickcernis** [comment] 2019-04-17 08:33
Thanks for sharing your test results, Jon, and for the extra info, @HankBrown.

Hank: it looks like you're running the earlier version of the `zip` script. If you switch to the new version in the develop branch you should get better results. You'd need to:

1. Copy the [`.scripts/makezip.js`](https://github.com/studiopress/genesis-sample/blob/develop/.scripts/makezip.js) script to your `.scripts` folder. You may need to edit the 'excludes' array in that file if you have added other development files (such as Sass) that you don't want to appear in the zip directory.
2. Update your [`package.json`](https://github.com/studiopress/genesis-sample/blob/develop/package.json) and [`package-lock.json`](https://github.com/studiopress/genesis-sample/blob/develop/package-lock.json) files. 
3. Run `npm ci` (to remove `node_modules` and install them afresh).
4. Try `npm run zip` again.

> Then I discover Design Pro doesn't work with the this theme!!

That's correct. Design Palette Pro supports the themes listed here: https://genesisdesignpro.com/themes/. Genesis Sample is generally intended to be modified via code, which may be why support isn't included.

> My real question is this: I wanted to use the sass partials given by the prometheus theme (https://github.com/srikat/genesis-sample-sass) , but they were generated for genesis 2.6, and genesis is now at 2.9.1... it is not clear to me if/how those get updated. Maybe they never will and it is up to us?

It looks like you've already opened an issue in the Prometheus repo to ask if it will be updated to work with Sample 2.9.1. Thanks for doing that! https://github.com/christophherr/prometheus/issues/54

I'll close this as it doesn't look like a bug in Genesis Sample, but feel free to reach out to me in Genesis Slack if you need further help with the `zip` command. https://studiopress.github.io/genesis/contribute/community/#genesiswp-slack-workspace

**Closed by nickcernis** 2019-04-17 08:33 UTC
Labels: bug
